import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";

import "./globals.css";
import Panels from "./components/panels";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Austin Hendricks Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Panels />
        <Analytics />
      </body>
    </html>
  );
}
